various changes

diff --git a/parser/Makefile b/parser/Makefile
--- a/parser/Makefile
+++ b/parser/Makefile
@@ -1,4 +1,4 @@
-# $Id: Makefile,v 1.11 2023/02/20 21:38:10 leavens Exp leavens $
+# $Id: Makefile,v 1.15 2023/03/17 03:00:59 leavens Exp leavens $
 # Makefile for lexer in COP 3402
 
 # Add .exe to the end of target to get that suffix in the rules
@@ -10,6 +10,8 @@ RM = rm -f
 SUBMISSIONZIPFILE = submission.zip
 ZIP = zip -9
 SOURCESLIST = sources.txt
+TESTFILES = hw3-asttest*.pl0 hw3-parseerrtest*.pl0 hw3-declerrtest*.pl0
+EXPECTEDOUTPUTS = `echo "$(TESTFILES)" | sed -e 's/\\.pl0/.out/g'`
 
 $(COMPILER): *.c *.h
 	$(CC) $(CFLAGS) -o $(COMPILER) `cat $(SOURCESLIST)`
@@ -30,7 +32,7 @@ clean:
 
 check-outputs: $(COMPILER) hw3-*test*.pl0
 	DIFFS=0; \
-	for f in `echo hw3-asttest*.pl0 hw3-parseerrtest*.pl0 hw3-declerrtest*.pl0 | sed -e 's/\\.pl0//g'`; \
+	for f in `echo $(TESTFILES) | sed -e 's/\\.pl0//g'`; \
 	do \
 		echo running "$$f.pl0"; \
 		./$(COMPILER) "$$f.pl0" >"$$f.myo" 2>&1; \
@@ -43,8 +45,11 @@ check-outputs: $(COMPILER) hw3-*test*.pl0
 		echo 'Test(s) failed!'; \
 	fi
 
-$(SUBMISSIONZIPFILE): sources.txt *.c *.h *.myo
-	$(ZIP) $(SUBMISSIONZIPFILE) sources.txt *.c *.h *.myo
+$(SUBMISSIONZIPFILE): $(SOURCESLIST) *.c *.h *.myo
+	$(ZIP) $(SUBMISSIONZIPFILE) $(SOURCESLIST) *.c *.h *.myo
+
+.PRECIOUS: $(SOURCESLIST)
+	echo *.c > $(SOURCESLIST)
 
 # developer's section below...
 
@@ -54,9 +59,16 @@ $(SUBMISSIONZIPFILE): sources.txt *.c *.h *.myo
 
 .PHONY: create-outputs
 create-outputs: $(COMPILER) hw3-*test*.pl0
-	for f in `echo hw3-asttest*.pl0 hw3-parseerrtest*.pl0 hw3-declerrtest*.pl0 | sed -e 's/\\.pl0//g'`; \
+	@echo 'Students should use the target check-outputs,'
+	@echo 'as using this target (create-outputs) will invalidate the tests'
+	@if test '$(IMTHEINSTRUCTOR)' != true ; \
+	then \
+		exit 1; \
+	fi; \
+	for f in `echo $(TESTFILES) | sed -e 's/\\.pl0//g'`; \
 	do \
 		echo running "$$f.pl0"; \
+		$(RM) "$$f.out"; \
 		./$(COMPILER) "$$f.pl0" >"$$f.out" 2>&1; \
 	done; \
 	echo done creating test outputs!
@@ -76,7 +88,7 @@ check-good-outputs: create-outputs
 	fi
 
 digest.txt: 
-	for f in `ls hw3-asttest*.pl0 hw3-parseerrtest*.pl0 hw3-declerrtest*.pl0 | sed -e 's/\\.pl0//g'`; \
+	for f in `ls $(TESTFILES) | sed -e 's/\\.pl0//g'`; \
         do cat $$f.pl0; echo " "; cat $$f.out; echo " "; echo " "; \
         done >digest.txt
 
@@ -91,7 +103,7 @@ PROVIDEDFILES = token.[ch] lexer_output.[ch] utilities.[ch] lexer.h \
 
 hw3-tests.zip: create-outputs $(TESTSZIPFILE)
 
-$(TESTSZIPFILE): hw3-*test*.pl0 Makefile $(PROVIDEDFILES)
+$(TESTSZIPFILE): $(TESTFILES) Makefile $(PROVIDEDFILES)
 	$(RM) $(TESTSZIPFILE)
-	chmod 755 hw3-*test*.pl0 hw3-*test*.out Makefile $(PROVIDEDFILES)
-	$(ZIP) $(TESTSZIPFILE) hw3-*test*.pl0 hw3-*test*.out Makefile $(PROVIDEDFILES)
+	chmod 444 $(TESTFILES) $(EXPECTEDOUTPUTS) Makefile $(PROVIDEDFILES)
+	$(ZIP) $(TESTSZIPFILE) $(TESTFILES) $(EXPECTEDOUTPUTS) Makefile $(PROVIDEDFILES)
